### ISSUE TITLE
ZH的第15周总结

### ISSUE THREAD

**Issue by fraser-in-school** [InspAlgo/TeamProject_BITCourse#14]
ZH周总结
因为这一周有算法考试，虽然当时好好学习了算法，但是真的结课时间太久了，很多知识都忘了，所以前几天主要是在复习算法，基本没有学习数据库。从周五开始学习和使用数据库。
在上一周里，我已经将MySQL的环境配置好了，成功的连接上了数据库，在这一周里，我想我的主要任务是把基本的几个表建立起来。但是进度却出乎意料的慢，主要还是error的问题，在我这一周开始去连接数据库的时候，却总是意外的出现error2003，刚开始我查找的时候，网上的解决办法啊都是修改密码。虽然我觉得我没有记错密码，但还是照着网上的各种教程去试了一试，但是看了十几个教程，竟然没有一个能用的，我想着是不是版本的问题，所以在mysql关键词后又加入了版本号，又搜到了两三个不同的教程，但是奇怪的是，一一试过之后仍然是error2003.
真的心态炸裂了。我花在mysql上的时间其实并不少了，而绝大多数的时间都花在排除各种各样的错误上了，实际上该干的工作基本没有动。
	后面队里的另一名同学数据库已经能够使用了，提出让我直接连接他的数据库就行。然后陆续的下了连个软件，第一个是 winSOC，第一个比较遗憾，到了最后一步，就是连接不上于是使用了第二个软件 putty， 着第二个软件连接却也着实花了一番功夫，不过最后总算是连接上了。还是上一张图吧！
 
然后也成功的和队友的建立的数据库连接上了。
 
可以查看表成员。
	但是现在有一个比较难的问题没有解决，我们该如何组建这个数据库。虽然数据关系图已经有了，但是，比较致命的是我们缺乏数据库的基本知识，不知道数据库是如何管理数据的，外部又是如何使用数据库的成员的，成员间又是怎样的互相连接的。我觉得我们需要好好的了解数据库的基础知识。以上。

**Comment by InspAlgo** [comment]
加油加油
